"""The rich-9 golden corpus is the engine's answer, and this file is what keeps it honest.

The pre-ranker (#9) scores every legal turn before the search's deadline is even consulted, so its
feature schema has to be one of the cheap ones. Nothing here reimplements a feature: the corpus is
generated by `tools/kcp13-golden` against a released engine, and these checks assert the shape of
what it wrote, so a regenerated file that quietly changed layout, precision or probe coverage fails
here rather than in a dataset built months later.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

GOLDEN = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "rich9"
KCP13 = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "kcp13"
SCHEMA_ID = "rich-9-v1"
FEATURE_COUNT = 9


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _corpora() -> list[Path]:
    return sorted(GOLDEN.glob("golden-engine-*.json"))


def test_at_least_one_corpus_is_committed() -> None:
    assert _corpora(), "no rich-9 golden corpus is committed"


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_corpus_declares_the_contract(path: Path) -> None:
    raw = _load(path)
    assert raw["schema"] == SCHEMA_ID
    assert raw["perspective"] == "side-to-move"
    assert len(raw["columns"]) == FEATURE_COUNT
    assert raw["engineArtifact"].startswith("com.fortemate:dicechess-engine")
    assert path.stem == f"golden-engine-{raw['engineVersion']}", "file name must name its engine"


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_every_probe_is_usable(path: Path) -> None:
    raw = _load(path)
    ids = [probe["id"] for probe in raw["probes"]]
    assert ids, "a corpus with no probes proves nothing"
    assert len(set(ids)) == len(ids), "duplicate probe ids"
    for probe in raw["probes"]:
        features = probe["features"]
        assert len(features) == FEATURE_COUNT, probe["id"]
        assert all(isinstance(value, (int, float)) for value in features), probe["id"]
        assert all(math.isfinite(value) for value in features), probe["id"]
        assert probe["side"] in ("w", "b"), probe["id"]


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_probe_set_matches_the_shared_source(path: Path) -> None:
    """Same probes.tsv, so the same ids — a schema that silently covers fewer positions than the
    others would make cross-schema comparisons quietly incomparable."""
    raw = _load(path)
    source = (KCP13 / "probes.tsv").read_text(encoding="utf-8").splitlines()
    expected = {line.split("\t")[0] for line in source[1:] if line.strip()}
    assert {probe["id"] for probe in raw["probes"]} == expected


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_colour_twins_are_present(path: Path) -> None:
    """The corpus carries mirrored pairs; a ranker trained on a schema that cannot tell them apart
    would be learning the board's orientation."""
    ids = {probe["id"] for probe in _load(path)["probes"]}
    twins = {name for name in ids if name.endswith("-twin")}
    assert twins, "no colour twins in the corpus"
    assert all(name[: -len("-twin")] in ids for name in twins)


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_rich9_is_the_kcp13_prefix(path: Path) -> None:
    """`kcp-13` is `rich-9` plus the four capture-probability columns — the expensive ones.

    Pinning the relation is what makes the pre-ranker's schema choice legible: the student sees
    exactly the part of the evaluator's input that does not cost a 216-outcome search. If the
    engine ever reorders either layout, that reasoning stops holding and this fails.
    """
    from dicechess_training.contracts import kcp13

    columns = tuple(_load(path)["columns"])
    assert columns == kcp13.COLUMN_NAMES[:FEATURE_COUNT]
    assert all("capture" in name for name in kcp13.COLUMN_NAMES[FEATURE_COUNT:])


@pytest.mark.parametrize("path", _corpora(), ids=lambda p: p.stem)
def test_values_equal_the_kcp13_corpus_on_the_shared_columns(path: Path) -> None:
    """The strongest check these fixtures can make of each other.

    Both corpora are produced by the same generator from the same probes, and `rich-9` is the
    `kcp-13` prefix, so on the nine shared columns the engine must have written identical numbers.
    A wrong extractor wired under this schema id, a corpus regenerated against a different engine,
    or a probe list that drifted apart all break this equality — using only committed evidence, with
    no JVM in the loop.

    What it cannot do is prove the engine still answers this way today; that needs a regeneration
    run, which no schema in this repository has in CI and which would make a Python-only test suite
    depend on sbt and a resolved engine artifact.
    """
    raw = _load(path)
    reference = _load(KCP13 / f"golden-engine-{raw['engineVersion']}.json")
    theirs = {probe["id"]: probe for probe in reference["probes"]}
    assert {probe["id"] for probe in raw["probes"]} == set(theirs)
    for probe in raw["probes"]:
        other = theirs[probe["id"]]
        assert probe["features"] == other["features"][:FEATURE_COUNT], probe["id"]
        assert (probe["fen"], probe["side"]) == (other["fen"], other["side"]), probe["id"]
        assert (probe.get("tags"), probe.get("note")) == (other.get("tags"), other.get("note"))
